version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

networks:
  backend:
    driver: bridge